services:
  andy-coin:
    build: .
    image: andy-coin:latest
    container_name: andy-coin
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RUST_LOG=info,serenity=error
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
